/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicAboutRouteImport } from './routes/(public)/about'
import { Route as publicBlogRouteRouteImport } from './routes/(public)/blog/route'
import { Route as publicFeedDotxmlRouteImport } from './routes/(public)/feed[.]xml'
import { Route as publicRobotsDottxtRouteImport } from './routes/(public)/robots[.]txt'
import { Route as publicSitemapDotxmlRouteImport } from './routes/(public)/sitemap[.]xml'
import { Route as publicApiContactRouteImport } from './routes/(public)/api.contact'
import { Route as publicBlogIndexRouteImport } from './routes/(public)/blog/index'
import { Route as publicBlogSlugRouteImport } from './routes/(public)/blog/$slug'
import { Route as publicBlogPreviewContentIdRouteImport } from './routes/(public)/blog/preview/$contentId'
import { Route as publicOgBlogSlugRouteImport } from './routes/(public)/og.blog.$slug'

const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicAboutRoute = publicAboutRouteImport.update({
  id: '/(public)/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const publicBlogRouteRoute = publicBlogRouteRouteImport.update({
  id: '/(public)/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const publicFeedDotxmlRoute = publicFeedDotxmlRouteImport.update({
  id: '/(public)/feed.xml',
  path: '/feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRobotsDottxtRoute = publicRobotsDottxtRouteImport.update({
  id: '/(public)/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const publicSitemapDotxmlRoute = publicSitemapDotxmlRouteImport.update({
  id: '/(public)/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const publicApiContactRoute = publicApiContactRouteImport.update({
  id: '/(public)/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const publicBlogIndexRoute = publicBlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicBlogRouteRoute,
} as any)
const publicBlogSlugRoute = publicBlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => publicBlogRouteRoute,
} as any)
const publicBlogPreviewContentIdRoute =
  publicBlogPreviewContentIdRouteImport.update({
    id: '/preview/$contentId',
    path: '/preview/$contentId',
    getParentRoute: () => publicBlogRouteRoute,
  } as any)
const publicOgBlogSlugRoute = publicOgBlogSlugRouteImport.update({
  id: '/(public)/og/blog/$slug',
  path: '/og/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/blog': typeof publicBlogRouteRouteWithChildren
  '/about': typeof publicAboutRoute
  '/feed.xml': typeof publicFeedDotxmlRoute
  '/robots.txt': typeof publicRobotsDottxtRoute
  '/sitemap.xml': typeof publicSitemapDotxmlRoute
  '/': typeof publicIndexRoute
  '/api/contact': typeof publicApiContactRoute
  '/blog/$slug': typeof publicBlogSlugRoute
  '/blog/': typeof publicBlogIndexRoute
  '/blog/preview/$contentId': typeof publicBlogPreviewContentIdRoute
  '/og/blog/$slug': typeof publicOgBlogSlugRoute
}
export interface FileRoutesByTo {
  '/about': typeof publicAboutRoute
  '/feed.xml': typeof publicFeedDotxmlRoute
  '/robots.txt': typeof publicRobotsDottxtRoute
  '/sitemap.xml': typeof publicSitemapDotxmlRoute
  '/': typeof publicIndexRoute
  '/api/contact': typeof publicApiContactRoute
  '/blog/$slug': typeof publicBlogSlugRoute
  '/blog': typeof publicBlogIndexRoute
  '/blog/preview/$contentId': typeof publicBlogPreviewContentIdRoute
  '/og/blog/$slug': typeof publicOgBlogSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)/blog': typeof publicBlogRouteRouteWithChildren
  '/(public)/about': typeof publicAboutRoute
  '/(public)/feed.xml': typeof publicFeedDotxmlRoute
  '/(public)/robots.txt': typeof publicRobotsDottxtRoute
  '/(public)/sitemap.xml': typeof publicSitemapDotxmlRoute
  '/(public)/': typeof publicIndexRoute
  '/(public)/api/contact': typeof publicApiContactRoute
  '/(public)/blog/$slug': typeof publicBlogSlugRoute
  '/(public)/blog/': typeof publicBlogIndexRoute
  '/(public)/blog/preview/$contentId': typeof publicBlogPreviewContentIdRoute
  '/(public)/og/blog/$slug': typeof publicOgBlogSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/blog'
    | '/about'
    | '/feed.xml'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/'
    | '/api/contact'
    | '/blog/$slug'
    | '/blog/'
    | '/blog/preview/$contentId'
    | '/og/blog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/feed.xml'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/'
    | '/api/contact'
    | '/blog/$slug'
    | '/blog'
    | '/blog/preview/$contentId'
    | '/og/blog/$slug'
  id:
    | '__root__'
    | '/(public)/blog'
    | '/(public)/about'
    | '/(public)/feed.xml'
    | '/(public)/robots.txt'
    | '/(public)/sitemap.xml'
    | '/(public)/'
    | '/(public)/api/contact'
    | '/(public)/blog/$slug'
    | '/(public)/blog/'
    | '/(public)/blog/preview/$contentId'
    | '/(public)/og/blog/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicBlogRouteRoute: typeof publicBlogRouteRouteWithChildren
  publicAboutRoute: typeof publicAboutRoute
  publicFeedDotxmlRoute: typeof publicFeedDotxmlRoute
  publicRobotsDottxtRoute: typeof publicRobotsDottxtRoute
  publicSitemapDotxmlRoute: typeof publicSitemapDotxmlRoute
  publicIndexRoute: typeof publicIndexRoute
  publicApiContactRoute: typeof publicApiContactRoute
  publicOgBlogSlugRoute: typeof publicOgBlogSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/about': {
      id: '/(public)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof publicAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/blog': {
      id: '/(public)/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof publicBlogRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/feed.xml': {
      id: '/(public)/feed.xml'
      path: '/feed.xml'
      fullPath: '/feed.xml'
      preLoaderRoute: typeof publicFeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/robots.txt': {
      id: '/(public)/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof publicRobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/sitemap.xml': {
      id: '/(public)/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof publicSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/api/contact': {
      id: '/(public)/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof publicApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/blog/': {
      id: '/(public)/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof publicBlogIndexRouteImport
      parentRoute: typeof publicBlogRouteRoute
    }
    '/(public)/blog/$slug': {
      id: '/(public)/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof publicBlogSlugRouteImport
      parentRoute: typeof publicBlogRouteRoute
    }
    '/(public)/blog/preview/$contentId': {
      id: '/(public)/blog/preview/$contentId'
      path: '/preview/$contentId'
      fullPath: '/blog/preview/$contentId'
      preLoaderRoute: typeof publicBlogPreviewContentIdRouteImport
      parentRoute: typeof publicBlogRouteRoute
    }
    '/(public)/og/blog/$slug': {
      id: '/(public)/og/blog/$slug'
      path: '/og/blog/$slug'
      fullPath: '/og/blog/$slug'
      preLoaderRoute: typeof publicOgBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface publicBlogRouteRouteChildren {
  publicBlogSlugRoute: typeof publicBlogSlugRoute
  publicBlogIndexRoute: typeof publicBlogIndexRoute
  publicBlogPreviewContentIdRoute: typeof publicBlogPreviewContentIdRoute
}

const publicBlogRouteRouteChildren: publicBlogRouteRouteChildren = {
  publicBlogSlugRoute: publicBlogSlugRoute,
  publicBlogIndexRoute: publicBlogIndexRoute,
  publicBlogPreviewContentIdRoute: publicBlogPreviewContentIdRoute,
}

const publicBlogRouteRouteWithChildren = publicBlogRouteRoute._addFileChildren(
  publicBlogRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  publicBlogRouteRoute: publicBlogRouteRouteWithChildren,
  publicAboutRoute: publicAboutRoute,
  publicFeedDotxmlRoute: publicFeedDotxmlRoute,
  publicRobotsDottxtRoute: publicRobotsDottxtRoute,
  publicSitemapDotxmlRoute: publicSitemapDotxmlRoute,
  publicIndexRoute: publicIndexRoute,
  publicApiContactRoute: publicApiContactRoute,
  publicOgBlogSlugRoute: publicOgBlogSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
